services:
  mail:
    image: stalwartlabs/mail-server:latest
    container_name: mail-${DOMAIN}
    restart: unless-stopped
    deploy:
    resources:
      limits:
        cpus: "0.50"
        memory: "256M"
      reservations:
        cpus: "0.25"
        memory: "128M"
    volumes:
      - ./config:/etc/stalwart:ro
      - mail_queue_${DOMAIN}:/var/stalwart/queue
    environment:
      - CACHE__REDIS__URL=redis://10.1.0.2:6379
      - DB__POSTGRES__URL=jdbc:postgresql://10.1.0.2:5432/${DB_NAME}
      - ADMIN__ENABLED=true
      - ADMIN__BIND=0.0.0.0:8080
      - ADMIN__TOKEN=${ADMIN_TOKEN}
    ports:
      - "${ADMIN_PORT}:8080"
    networks:
      - mail_net
    

volumes:
  mail_queue_${DOMAIN}:

networks:
  mail_net:
    external: true

